### ISSUE TITLE
feat: make it possible to make options required for actions

### ISSUE THREAD

**Issue by divramod** [fentas/argsh#9]
As  a developer I want to be able to define options which are required to be passed to run an action.

## todo
* [ ] variant 1: in the action definition: make it possible to pass options with their short names to make them required

## possible implementations
```
# example for defining it in the actions definition
# req --> requires

# args(F|floating-ips-delete): des(Create the passed floating ips.) req(p,c)
```
* [ ] variant 2: in the option definition: make it possible to pass actions whith their short or long names to make them depend on this option
```
# example for defining it in the options definition
# reqb --> required by

# args(p|playbook-name): opt(PLAYBOOK_NAME) def(test) des(The playbook name.) val() reqb(D)
```

**Comment by fentas** [comment]
You can use `val()` for that now. You can define `val` for actions validating arguments.
